[project]
name = "encrypted-udp-jpeg-stream"
version = "0.1.0"
description = "A simple project for transmitting encrypted images over UDP using symmetric key."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "opencv-python",
    "cryptography",
    "numpy"
]
